project_id = "mymenu"

[api]
enabled = true

[auth]
enabled = true
enable_anonymous_sign_ins = true

[db]
major_version = 15

[storage]
enabled = true

[storage.buckets.processing-media]
public = false
file_size_limit = "20MiB"
allowed_mime_types = ["image/jpeg", "image/png", "image/heic", "image/heif"]

[edge_runtime]
policy = "per_worker"

[functions.process-ai-jobs]
enabled = true
verify_jwt = false

[functions.processing-jobs]
enabled = true
verify_jwt = true

[functions.cleanup-processing-jobs]
enabled = true
verify_jwt = false

[functions.service-account]
enabled = true
verify_jwt = true
